language: ruby
rvm:
  - 1.9.3
env:
  - SECRET_TOKEN="foo" TWILIO_ACCOUNT_SID="foo" TWILIO_AUTH_TOKEN="foo" TWILIO_NUMBER="+15175551212"
bundler_args: --without local
script: 
  - bundle exec rake spec
before_install:
  - sudo apt-get update -qq
before_script:
  - createuser -s reveille
  - rake db:create:all
  - rake db:migrate
  - rake db:test:prepare
branches:
  only:
    - master